import { getAllArtifacts } from "@/lib/db";
import { ArtifactCard } from "@/components/ArtifactCard";

export const dynamic = "force-static";
export const revalidate = 3600;

export default function HomePage() {
  const artifacts = getAllArtifacts();

  return (
    <div className="max-w-3xl mx-auto px-6">
      <header className="py-10 border-b border-[var(--color-border)]">
        <h1 className="text-xs tracking-[0.3em] uppercase text-[var(--color-dim)] mb-3">
          Hermes Archaeology
        </h1>
        <p className="text-lg font-light leading-relaxed max-w-xl">
          Software history rendered as interface archaeology.
        </p>
        <p className="text-sm text-[var(--color-dim)] mt-2 leading-relaxed max-w-xl">
          The Hermes Agent examines its own codebase evolution and generates
          post-internet artifacts. Each artifact is a program. The agent&apos;s memory
          and process are part of the artwork.
        </p>
        <div className="mt-4 flex gap-6 text-[10px] text-[var(--color-dim)] tracking-wide">
          <span>// NousResearch/hermes-agent</span>
          <span>// {artifacts.length} artifacts</span>
          <span>// generated by Hermes Agent</span>
        </div>
      </header>

      <div>
        {artifacts.map((art) => (
          <ArtifactCard
            key={art.id}
            date={art.date}
            tag={art.tag}
            filename={art.filename}
            reflection={art.reflection}
            aestheticUsed={JSON.parse(art.aesthetic_used)}
            releaseName={art.release_name}
          />
        ))}
      </div>
    </div>
  );
}
